// <auto-generated />
using System;
using HotByte.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotByte.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531144610_AddUserAddressSupport")]
    partial class AddUserAddressSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotByte.API.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HotByte.API.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HotByte.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Start your day right with our delicious breakfast options",
                            ImageUrl = "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666",
                            IsActive = true,
                            MealType = "Breakfast",
                            Name = "Breakfast"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Juicy gourmet burgers with premium toppings",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
                            IsActive = true,
                            MealType = "All Day",
                            Name = "Burgers"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Handcrafted pizzas with fresh ingredients",
                            ImageUrl = "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38",
                            IsActive = true,
                            MealType = "All Day",
                            Name = "Pizza"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Authentic Middle Eastern flavors and grills",
                            ImageUrl = "https://images.unsplash.com/photo-1529006557810-274b9b2fc783",
                            IsActive = true,
                            MealType = "Lunch",
                            Name = "Arabian"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Sweet treats to end your meal on a high note",
                            ImageUrl = "https://images.unsplash.com/photo-1551024506-0bccd828d307",
                            IsActive = true,
                            MealType = "All Day",
                            Name = "Desserts"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Refreshing drinks and shakes",
                            ImageUrl = "https://images.unsplash.com/photo-1544145945-f90425340c7e",
                            IsActive = true,
                            MealType = "All Day",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("HotByte.API.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<string>("AvailableTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<decimal?>("Carbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CookingTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Fats")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVeg")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Proteins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("TasteInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            AvailableTime = "Breakfast",
                            Calories = 350,
                            Carbohydrates = 55.0m,
                            CategoryId = 1,
                            CookingTime = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crispy rice crepe filled with spiced potato masala, served with sambar and coconut chutney",
                            DiscountPrice = 99.00m,
                            Fats = 12.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1630383249896-424e482df921",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Masala Dosa",
                            Price = 120.00m,
                            Proteins = 8.5m,
                            RestaurantId = 1,
                            TasteInfo = "Spicy Light"
                        },
                        new
                        {
                            MenuItemId = 2,
                            AvailableTime = "Breakfast",
                            Calories = 280,
                            Carbohydrates = 45.0m,
                            CategoryId = 1,
                            CookingTime = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft steamed rice cakes with crispy medu vada, served with sambar and chutneys",
                            Fats = 8.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1589301760014-d929f3979dbc",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Idli Vada Combo",
                            Price = 90.00m,
                            Proteins = 7.0m,
                            RestaurantId = 1,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 3,
                            AvailableTime = "Lunch",
                            Calories = 650,
                            Carbohydrates = 60.0m,
                            CategoryId = 4,
                            CookingTime = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tender marinated chicken wrapped in pita with garlic sauce, hummus, pickles, and fries",
                            DiscountPrice = 189.00m,
                            Fats = 28.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1529006557810-274b9b2fc783",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Shawarma Plate",
                            Price = 220.00m,
                            Proteins = 35.0m,
                            RestaurantId = 1,
                            TasteInfo = "Spicy Light"
                        },
                        new
                        {
                            MenuItemId = 4,
                            AvailableTime = "All Day",
                            Calories = 480,
                            Carbohydrates = 55.0m,
                            CategoryId = 4,
                            CookingTime = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crispy chickpea falafel in warm pita with tahini, fresh salad, and pickled vegetables",
                            Fats = 20.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1593001874117-c99c800e3eb7",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Falafel Wrap",
                            Price = 180.00m,
                            Proteins = 18.0m,
                            RestaurantId = 1,
                            TasteInfo = "Spicy Light"
                        },
                        new
                        {
                            MenuItemId = 5,
                            AvailableTime = "All Day",
                            Calories = 380,
                            Carbohydrates = 58.0m,
                            CategoryId = 5,
                            CookingTime = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft milk-solid dumplings soaked in rose-flavored sugar syrup",
                            Fats = 15.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1666190073498-2a23c97508a0",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Gulab Jamun (4 pcs)",
                            Price = 100.00m,
                            Proteins = 5.0m,
                            RestaurantId = 1,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 6,
                            AvailableTime = "All Day",
                            Calories = 220,
                            Carbohydrates = 40.0m,
                            CategoryId = 6,
                            CookingTime = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Creamy yogurt blended with fresh Alphonso mango pulp and a hint of cardamom",
                            Fats = 4.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1626200419199-391ae4be7a41",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Mango Lassi",
                            Price = 80.00m,
                            Proteins = 6.0m,
                            RestaurantId = 1,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 7,
                            AvailableTime = "All Day",
                            Calories = 720,
                            Carbohydrates = 48.0m,
                            CategoryId = 2,
                            CookingTime = 18,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Double smashed beef patty with American cheese, caramelized onions, pickles, and secret sauce",
                            DiscountPrice = 199.00m,
                            Fats = 38.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Classic Smash Burger",
                            Price = 249.00m,
                            Proteins = 42.0m,
                            RestaurantId = 2,
                            TasteInfo = "Spicy Light"
                        },
                        new
                        {
                            MenuItemId = 8,
                            AvailableTime = "All Day",
                            Calories = 850,
                            Carbohydrates = 52.0m,
                            CategoryId = 2,
                            CookingTime = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grilled beef patty with crispy bacon, cheddar, onion rings, and smoky BBQ sauce",
                            Fats = 45.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1553979459-d2229ba7433b",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "BBQ Bacon Burger",
                            Price = 299.00m,
                            Proteins = 48.0m,
                            RestaurantId = 2,
                            TasteInfo = "Spicy Full"
                        },
                        new
                        {
                            MenuItemId = 9,
                            AvailableTime = "All Day",
                            Calories = 520,
                            Carbohydrates = 58.0m,
                            CategoryId = 2,
                            CookingTime = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crispy vegetable patty with lettuce, tomato, jalapeños, and chipotle mayo",
                            DiscountPrice = 169.00m,
                            Fats = 22.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1520072959219-c595dc870360",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Veggie Supreme Burger",
                            Price = 199.00m,
                            Proteins = 18.0m,
                            RestaurantId = 2,
                            TasteInfo = "Spicy Light"
                        },
                        new
                        {
                            MenuItemId = 10,
                            AvailableTime = "All Day",
                            Calories = 450,
                            Carbohydrates = 62.0m,
                            CategoryId = 5,
                            CookingTime = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm chocolate cake with a molten chocolate center, served with vanilla ice cream",
                            Fats = 22.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1624353365286-3f8d62daad51",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Chocolate Lava Cake",
                            Price = 180.00m,
                            Proteins = 6.0m,
                            RestaurantId = 2,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 11,
                            AvailableTime = "All Day",
                            Calories = 480,
                            Carbohydrates = 68.0m,
                            CategoryId = 6,
                            CookingTime = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thick and creamy milkshake loaded with crushed Oreo cookies and whipped cream",
                            Fats = 18.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1572490122747-3968b75cc699",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Oreo Milkshake",
                            Price = 150.00m,
                            Proteins = 10.0m,
                            RestaurantId = 2,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 12,
                            AvailableTime = "All Day",
                            Calories = 280,
                            Carbohydrates = 38.0m,
                            CategoryId = 6,
                            CookingTime = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chilled coffee blended with milk, cream, and a touch of chocolate syrup",
                            Fats = 10.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1461023058943-07fcbe16d735",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Cold Coffee",
                            Price = 120.00m,
                            Proteins = 8.0m,
                            RestaurantId = 2,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 13,
                            AvailableTime = "All Day",
                            Calories = 680,
                            Carbohydrates = 85.0m,
                            CategoryId = 3,
                            CookingTime = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic wood-fired pizza with San Marzano tomato sauce, fresh mozzarella, and basil",
                            DiscountPrice = 249.00m,
                            Fats = 22.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Margherita Pizza",
                            Price = 299.00m,
                            Proteins = 28.0m,
                            RestaurantId = 3,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 14,
                            AvailableTime = "All Day",
                            Calories = 820,
                            Carbohydrates = 82.0m,
                            CategoryId = 3,
                            CookingTime = 22,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Loaded with spicy pepperoni, mozzarella, and our signature marinara sauce",
                            DiscountPrice = 349.00m,
                            Fats = 35.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1628840042765-356cda07504e",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Pepperoni Pizza",
                            Price = 399.00m,
                            Proteins = 38.0m,
                            RestaurantId = 3,
                            TasteInfo = "Spicy Light"
                        },
                        new
                        {
                            MenuItemId = 15,
                            AvailableTime = "All Day",
                            Calories = 780,
                            Carbohydrates = 78.0m,
                            CategoryId = 3,
                            CookingTime = 25,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grilled chicken, red onions, bell peppers, and jalapeños on a smoky BBQ base",
                            Fats = 30.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "BBQ Chicken Pizza",
                            Price = 449.00m,
                            Proteins = 40.0m,
                            RestaurantId = 3,
                            TasteInfo = "Spicy Full"
                        },
                        new
                        {
                            MenuItemId = 16,
                            AvailableTime = "All Day",
                            Calories = 650,
                            Carbohydrates = 80.0m,
                            CategoryId = 3,
                            CookingTime = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mushrooms, olives, capsicum, corn, onions, and tomatoes with extra cheese",
                            DiscountPrice = 299.00m,
                            Fats = 24.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Farm Fresh Veggie Pizza",
                            Price = 349.00m,
                            Proteins = 22.0m,
                            RestaurantId = 3,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 17,
                            AvailableTime = "All Day",
                            Calories = 380,
                            Carbohydrates = 48.0m,
                            CategoryId = 5,
                            CookingTime = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream",
                            Fats = 18.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Tiramisu",
                            Price = 220.00m,
                            Proteins = 6.0m,
                            RestaurantId = 3,
                            TasteInfo = "Sweet"
                        },
                        new
                        {
                            MenuItemId = 18,
                            AvailableTime = "All Day",
                            Calories = 80,
                            Carbohydrates = 20.0m,
                            CategoryId = 6,
                            CookingTime = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freshly squeezed lime with soda, mint, and your choice of sweet or salted",
                            Fats = 0.0m,
                            ImageUrl = "https://images.unsplash.com/photo-1513558161293-cdaf765ed514",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Fresh Lime Soda",
                            Price = 60.00m,
                            Proteins = 0.5m,
                            RestaurantId = 3,
                            TasteInfo = "Sweet"
                        });
                });

            modelBuilder.Entity("HotByte.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HotByte.API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<decimal>("ItemTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HotByte.API.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Authentic South Indian & North Indian cuisine with a modern twist. Known for our aromatic biryanis and rich curries.",
                            Email = "contact@spicegarden.com",
                            ImageUrl = "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
                            IsActive = true,
                            Location = "45 Anna Nagar, Chennai, Tamil Nadu 600040",
                            Name = "Spice Garden",
                            PasswordHash = "$2a$11$Ie..HR8H5/6YIpBb4et6P.TwHp62a4NBuWfp7wG.akenaTpHPpljW",
                            PhoneNumber = "9111222333"
                        },
                        new
                        {
                            RestaurantId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gourmet burgers made with premium ingredients. Juicy patties, fresh veggies, and secret sauces.",
                            Email = "hello@burgerbarn.com",
                            ImageUrl = "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17",
                            IsActive = true,
                            Location = "12 MG Road, Bangalore, Karnataka 560001",
                            Name = "Burger Barn",
                            PasswordHash = "$2a$11$Ie..HR8H5/6YIpBb4et6P.TwHp62a4NBuWfp7wG.akenaTpHPpljW",
                            PhoneNumber = "9222333444"
                        },
                        new
                        {
                            RestaurantId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wood-fired pizzas with handmade dough, imported cheese, and fresh toppings. Italian flavors at your doorstep.",
                            Email = "order@pizzapalace.com",
                            ImageUrl = "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
                            IsActive = true,
                            Location = "88 Jubilee Hills, Hyderabad, Telangana 500033",
                            Name = "Pizza Palace",
                            PasswordHash = "$2a$11$Ie..HR8H5/6YIpBb4et6P.TwHp62a4NBuWfp7wG.akenaTpHPpljW",
                            PhoneNumber = "9333444555"
                        });
                });

            modelBuilder.Entity("HotByte.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@hotbyte.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$APYGzGiIm7dO4oWMit/ACOOuvPNcsRSI6dYlTnq3Mz0Zyo3McMdpa",
                            PhoneNumber = "0000000000",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "123 Main Street, Chennai",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            FirstName = "John",
                            Gender = "Male",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$75yFIf0UbgpoUlb5e9biuOF.pBpl79K6oK6VtRGP/0/gwiENyTKje",
                            PhoneNumber = "9876543210",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("HotByte.API.Models.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            AddressLabel = "Home",
                            AddressLine = "123 Main Street",
                            City = "Chennai",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PostalCode = "600001",
                            State = "Tamil Nadu",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("HotByte.API.Models.Cart", b =>
                {
                    b.HasOne("HotByte.API.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("HotByte.API.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotByte.API.Models.CartItem", b =>
                {
                    b.HasOne("HotByte.API.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotByte.API.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("HotByte.API.Models.MenuItem", b =>
                {
                    b.HasOne("HotByte.API.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotByte.API.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("HotByte.API.Models.Order", b =>
                {
                    b.HasOne("HotByte.API.Models.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotByte.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotByte.API.Models.OrderItem", b =>
                {
                    b.HasOne("HotByte.API.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotByte.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HotByte.API.Models.UserAddress", b =>
                {
                    b.HasOne("HotByte.API.Models.User", "User")
                        .WithMany("SavedAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotByte.API.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("HotByte.API.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("HotByte.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HotByte.API.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HotByte.API.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("SavedAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
